### ISSUE TITLE
当OKex接口调用调用stop后再调用connect报错，报错信息为：There is no current event loop in thread 'Thread-6'.

### ISSUE THREAD

**Issue by sunmichace** [vnpy/vnpy_rest#1]
想请教一下：当OKex接口调用调用stop后再调用connect报错，报错信息为：There is no current event loop in thread 'Thread-6'.
调用gateway.close后调用gateway.connect，想重新连接上时候报错。请问一下这个问题如何解决呢？
谢谢您

**Comment by vnpy** [comment]
请问使用的是最新的2.3.0版本吗？

**Comment by sunmichace** [comment]
对的。在vnpy中，开了同样一个帖子。链接地址：https://github.com/vnpy/vnpy/issues/3022。所以内容在那里补充一下。
环境
操作系统: Windows 10
Python版本: python3.7
vn.py版本: v2.3.0
Issue类型
三选一：Question

预期程序行为
针对Okex接口，设计了断开重连的代码，调用self.gateway.close()，之后调用self.gateway.connect()。预期gateway能继续连接上交易所数据。

实际程序行为
调用过程中，报错出现在self.gateway.connect()中，在调用OkexRestApi.connect中的self.start(session_number)报错。在启用start_event_loop()中报错。

重现步骤
针对Bug类型Issue，请提供具体重现步骤以及报错截图，流程：

self.gateway.close()（完成不报错）-->self.gateway.connect(报错)-->OkexRestApi.connect-->错误出现在start_event_loop

image
报错信息：There is no current event loop in thread 'Thread-6'

**Comment by vnpy** [comment]
收到，我们一起来排查下

**Comment by sunmichace** [comment]
没问题，我这里提供我的试错经验。我查了网上的解决办法：
1.很多中文帖子，建议这种解决办法：https://blog.csdn.net/longe20111104/article/details/116641176。也出现报错。它是建议直接建一个新的事件循环
2.这个帖子，我认为是为啥上述方法解决不到的主要原因【“在主线程中，调用get_event_loop总能返回属于主线程的event loop对象，如果是处于非主线程中，还需要调用set_event_loop方法指定一个event loop对象，这样get_event_loop才会获取到被标记的event loop对象：”】，但我看得不太明白。https://www.cnblogs.com/SunshineKimi/p/12053914.html。请大佬过目

**Comment by vnpy** [comment]
已修复
