### ISSUE TITLE
cannot import name 'Response' from 'vnpy_rest'

### ISSUE THREAD

**Issue by yhmickey** [vnpy/vnpy_rest#3]
vnpy 2.3.0
测试了一下，报这个错误。
应该怎么弄呢？

from vnpy_rest import RestClient, Request, Response

ImportError: cannot import name 'Response' from 'vnpy_rest' (C:\ProgramData\Miniconda3\envs\vnpy\lib\site-packages\vnpy_rest\__init__.py)

**Comment by vnpy** [comment]
请升级到2.5.0即可
