### ISSUE TITLE
okex调用rest_client 报错www.okx.com:443

### ISSUE THREAD

**Issue by jQizhang** [vnpy/vnpy_rest#7]
![640adbab-e42e-4971-9a52-cabb96a19dc8](https://user-images.githubusercontent.com/22980766/218283121-12238f0f-f188-4585-a899-6bec0746551f.jpeg)

经过排查发现，rest_client.py的117行默认proxy=“”，
![image](https://user-images.githubusercontent.com/22980766/218283212-3ddcec0b-bb9c-4d5e-86bb-1a4f918ccf8f.png)

在aiohttp中判断逻辑为None
![image](https://user-images.githubusercontent.com/22980766/218283183-a3fa49c6-217f-461c-b147-3425567e2157.png)

需要将117行改为: self.proxy=None

**Comment by vnpy** [comment]
收到，我们来修改下

**Comment by vnpy** [comment]
已经修复，感谢反馈
