### ISSUE TITLE
WindowsSelectorEventLoopPolicy

### ISSUE THREAD

**Issue by Yize9** [vnpy/vnpy_rest#8]
linux无法导入WindowsSelectorEventLoopPolicy

**Comment by Yize9** [comment]
@vnpy 这是一个bug，WindowsSelectorEventLoopPolicy只用于windows，在linux导入的时候没有做平台区分判断，导致编程错误，我提交了合并请求https://github.com/vnpy/vnpy_rest/pulls

**Comment by vnpy** [comment]
感谢PR，我们会测试后在下个版本中发布

**Comment by vnpy** [comment]
已经合并，非常感谢
